-- Ejecutar en el SQL Editor de Supabase. Todas las tablas quedan aisladas por hogar.
create extension if not exists "pgcrypto";
create table public.households (id uuid primary key default gen_random_uuid(), name text not null, created_at timestamptz not null default now());
create table public.household_members (id uuid primary key default gen_random_uuid(), household_id uuid not null references public.households(id) on delete cascade, user_id uuid not null references auth.users(id) on delete cascade, display_name text not null, role text not null default 'member' check (role in ('owner','member')), unique(household_id,user_id));
create table public.shopping_tickets (id uuid primary key default gen_random_uuid(), household_id uuid not null references public.households(id) on delete cascade, date date not null default current_date, created_by uuid references auth.users(id), created_at timestamptz not null default now());
create table public.shopping_items (id uuid primary key default gen_random_uuid(), ticket_id uuid not null references public.shopping_tickets(id) on delete cascade, product_name text not null, quantity text default '1', checked boolean not null default false, created_at timestamptz not null default now());
create table public.furniture_rooms (id uuid primary key default gen_random_uuid(), household_id uuid not null references public.households(id) on delete cascade, name text not null, unique(household_id,name));
create table public.furniture_items (id uuid primary key default gen_random_uuid(), household_id uuid not null references public.households(id) on delete cascade, room_id uuid references public.furniture_rooms(id) on delete set null, title text not null, url text, priority int not null default 3 check(priority between 1 and 5), image_url text, description text, price numeric(12,2), site_name text, status text not null default 'pending', created_by uuid references auth.users(id), created_at timestamptz not null default now());
create table public.tasks (id uuid primary key default gen_random_uuid(), household_id uuid not null references public.households(id) on delete cascade, title text not null, description text, created_at timestamptz not null default now());
create table public.task_assignments (id uuid primary key default gen_random_uuid(), task_id uuid not null references public.tasks(id) on delete cascade, assigned_to uuid references auth.users(id), date date not null, is_recurring boolean not null default false, recurrence_rule text, completed boolean not null default false);
create table public.expense_types (id uuid primary key default gen_random_uuid(), household_id uuid not null references public.households(id) on delete cascade, name text not null, unique(household_id,name));
create table public.expenses (id uuid primary key default gen_random_uuid(), household_id uuid not null references public.households(id) on delete cascade, type text not null, detail text not null, amount numeric(12,2) not null check(amount >= 0), date date not null default current_date, created_by uuid references auth.users(id), created_at timestamptz not null default now());
create table public.household_notes (id uuid primary key default gen_random_uuid(), household_id uuid not null references public.households(id) on delete cascade, content text not null check(length(trim(content)) > 0), checked boolean not null default false, created_by uuid references auth.users(id), created_at timestamptz not null default now());

create or replace function public.is_household_member(target_household uuid) returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from household_members where household_id=target_household and user_id=auth.uid()) $$;
create or replace function public.is_household_owner(target_household uuid) returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from household_members where household_id=target_household and user_id=auth.uid() and role='owner') $$;
alter table public.households enable row level security; alter table public.household_members enable row level security; alter table public.shopping_tickets enable row level security; alter table public.shopping_items enable row level security; alter table public.furniture_rooms enable row level security; alter table public.furniture_items enable row level security; alter table public.tasks enable row level security; alter table public.task_assignments enable row level security; alter table public.expense_types enable row level security; alter table public.expenses enable row level security; alter table public.household_notes enable row level security;
create policy "members access household" on households for select using (is_household_member(id));
create policy "members see members" on household_members for select using (is_household_member(household_id));
create policy "owners manage members" on household_members for all using (is_household_owner(household_id)) with check (is_household_owner(household_id));
create policy "ticket household access" on shopping_tickets for all using (is_household_member(household_id)) with check (is_household_member(household_id));
create policy "item through ticket access" on shopping_items for all using (exists(select 1 from shopping_tickets t where t.id=ticket_id and is_household_member(t.household_id))) with check (exists(select 1 from shopping_tickets t where t.id=ticket_id and is_household_member(t.household_id)));
create policy "room household access" on furniture_rooms for all using (is_household_member(household_id)) with check (is_household_member(household_id));
create policy "furniture household access" on furniture_items for all using (is_household_member(household_id)) with check (is_household_member(household_id));
create policy "task household access" on tasks for all using (is_household_member(household_id)) with check (is_household_member(household_id));
create policy "assignment through task access" on task_assignments for all using (exists(select 1 from tasks t where t.id=task_id and is_household_member(t.household_id))) with check (exists(select 1 from tasks t where t.id=task_id and is_household_member(t.household_id)));
create policy "expense type access" on expense_types for all using (is_household_member(household_id)) with check (is_household_member(household_id));
create policy "expense household access" on expenses for all using (is_household_member(household_id)) with check (is_household_member(household_id));
create policy "note household access" on household_notes for all using (is_household_member(household_id)) with check (is_household_member(household_id));
